spring.application.name=lab
server.port=8081

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:lab
spring.datasource.username=labemt
spring.datasource.password=labemt
spring.jpa.hibernate.ddl-auto=create-drop

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2

# Swagger Configurations
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
